### Index ile Elemanlara Erişmek

#### Tek Boyutlu Array

In [1]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([1, 3, 3, 4, 3, 7, 8, 4, 8, 5])

In [2]:
a[0]

1

In [6]:
a[-1] #tersten erişim, sondaki eleman

5

In [7]:
a[0] = 100 #ilk elemanı değiştirdik
a

array([100,   3,   3,   4,   3,   7,   8,   4,   8,   5])

#### İki Boyutlu Array

In [9]:
a = np.random.randint(10, size = (3, 5))
a

array([[9, 6, 7, 7, 7],
       [1, 6, 3, 5, 6],
       [1, 4, 0, 1, 6]])

In [10]:
 a[0][0]

9

In [12]:
a[1][4] = 99
a

array([[ 9,  6,  7,  7,  7],
       [ 1,  6,  3,  5, 99],
       [ 1,  4,  0,  1,  6]])

In [14]:
a[1][4] = 2.7 #array tipi int olduğu için, ondalık kısmı keserek ekleme yapar. (2.7 yerine 2 olarak değiştirir)
a

array([[9, 6, 7, 7, 7],
       [1, 6, 3, 5, 2],
       [1, 4, 0, 1, 6]])

### Slicing ile Elemanlara Erişmek (Array Alt Kümelerine Erişmek)

#### Tek Boyutlu Array

In [15]:
import numpy as np
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
a[0:3] #0'dan 3'e kadar seçme işlemi

array([20, 21, 22])

In [18]:
a[:3] #ilk eleman verilmezse, arrayin başından başlar

array([20, 21, 22])

In [20]:
a[3:] #3. indexte, array sonuna kadar okur

array([23, 24, 25, 26, 27, 28, 29])

In [22]:
a[1::2] #1. indexten başlar, 2'şer 2'şer artarak okuma yapar.

array([21, 23, 25, 27, 29])

#### İki Boyutlu Array

In [23]:
a = np.random.randint(10, size = (5, 5))
a

array([[6, 2, 1, 2, 4],
       [3, 8, 0, 2, 5],
       [7, 1, 0, 0, 3],
       [1, 3, 4, 3, 1],
       [7, 9, 6, 8, 8]])

In [26]:
a[:, 0] #ilk sütuna erişir

array([6, 3, 7, 1, 7])

In [27]:
a[:, 4] #son sütuna erişir

array([4, 5, 3, 1, 8])

In [28]:
a[0, :] #ilk satıra erişir

array([6, 2, 1, 2, 4])

In [30]:
a[4, :] #son satıra erişir

array([7, 9, 6, 8, 8])

In [31]:
a[0:2, 0:3]

array([[6, 2, 1],
       [3, 8, 0]])

In [32]:
a[::, :2] #tüm satırları, 2. sütuna kadar al.

array([[6, 2],
       [3, 8],
       [7, 1],
       [1, 3],
       [7, 9]])

In [33]:
a[1:3, 0:2]

array([[3, 8],
       [7, 1]])

### Alt Küme Üzerinde İşlem Yapmak

* Bazen ana array üzerinde değişiklik yapmadan, sadece alt array üzerinde değişiklik yapılmak istenebilir.
* Alt array üzerinde yapılan değişikliğin, ana arrayi etkilememesi nasıl sağlanır?

In [34]:
a = np.random.randint(10, size = (5, 5))
a

array([[6, 3, 4, 4, 4],
       [5, 8, 9, 1, 8],
       [3, 8, 0, 3, 2],
       [5, 6, 0, 5, 9],
       [6, 9, 1, 2, 9]])

In [35]:
altA = a[0:3, 0:2]
altA

array([[6, 3],
       [5, 8],
       [3, 8]])

In [36]:
altA[0][0] = 9999
altA[1][1] = 888
altA

array([[9999,    3],
       [   5,  888],
       [   3,    8]])

In [38]:
 a #değişiklik burada da meydana geldi.

array([[9999,    3,    4,    4,    4],
       [   5,  888,    9,    1,    8],
       [   3,    8,    0,    3,    2],
       [   5,    6,    0,    5,    9],
       [   6,    9,    1,    2,    9]])

In [39]:
a = np.random.randint(10, size = (5, 5))
a

array([[6, 6, 8, 4, 6],
       [2, 0, 1, 8, 1],
       [0, 1, 5, 9, 6],
       [7, 4, 7, 6, 5],
       [2, 4, 2, 7, 8]])

In [40]:
altB = a[0:3, 0:2].copy() #copy() metodu ana arrayin etkilenmemesini sağlar.
altB

array([[6, 6],
       [2, 0],
       [0, 1]])

In [41]:
altB[0][0] = 9999
altB[1][1] = 888
altB

array([[9999,    6],
       [   2,  888],
       [   0,    1]])

In [43]:
a #bu arrayde değişiklik olmadı

array([[6, 6, 8, 4, 6],
       [2, 0, 1, 8, 1],
       [0, 1, 5, 9, 6],
       [7, 4, 7, 6, 5],
       [2, 4, 2, 7, 8]])

### Fancy Index ile Elemanlara Erişmek

#### Tek Boyutlu Array

In [44]:
import numpy as np
a = np.arange(0, 30, 3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [45]:
a[1]

3

In [46]:
a[3]

9

In [47]:
a[5]

15

In [48]:
[a[1], a[3], a[5]]

[3, 9, 15]

In [49]:
getir = [1, 3, 5]

In [50]:
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [52]:
a[getir] #getir arrayi içerisindeki indexlere ait elemanları getirir.

array([ 3,  9, 15])

#### İki Boyutlu Array

In [62]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
row = np.array([0, 1])
column = np.array([1, 2])

In [70]:
a[row, column]

array([1, 5])

### Koşullu Eleman İşlemleri

In [72]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [73]:
a > 5 #array içerisindeki her bir eleman için >5 kontrolü yapar.

array([False, False, False, False, False])

In [74]:
a < 3

array([ True,  True, False, False, False])

In [75]:
a[a < 3] #fancy ile istediğimiz koşula uygun elemanlara bu şekilde ulaşabiliriz.

array([1, 2])

In [76]:
a[a >= 3]

array([3, 4, 5])

In [77]:
a[a == 3]

array([3])

In [78]:
a[a != 3]

array([1, 2, 4, 5])

In [79]:
a * 2 #her elemanları 2 ile çarpar.

array([ 2,  4,  6,  8, 10])

In [80]:
a / 5 #her elemanları 5'e böler.

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [81]:
a*5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [83]:
a ** 2 #her elemanın karesini alır

array([ 1,  4,  9, 16, 25], dtype=int32)

### Matematiksel İşlemler

In [84]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [88]:
a / 5 #ufunc kavramı

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [89]:
np.divide(a, 5)

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [90]:
np.mod(a, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [92]:
np.absolute(np.array([-3])) #mutlak değer

array([3])

In [93]:
np.sin(360)

0.9589157234143065

In [94]:
np.cos(180)

-0.5984600690578581

In [95]:
a = np.array([1, 2, 3])

In [96]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [97]:
np.log2(a)

array([0.       , 1.       , 1.5849625])

In [102]:
?np 

In [103]:
#numpy üzerinde kullanılabilecek işlemler
#googleda aramak istediğin kütüphaneyi yazıp, sonuna cheatsheet ekleyerek o kütüphane ile ilgili derli toplu dokümanlara ulaşılabilir.

### NumPy ile İki Bilinmeyenli Denklem Çözümü

In [104]:
import numpy as np

In [107]:
a = np.array([[5, 1], [1, 3]]) #bilinmeyenlerin katsayıları
b = np.array([12, 10])

In [108]:
a

array([[5, 1],
       [1, 3]])

In [109]:
b

array([12, 10])

In [111]:
x = np.linalg.solve(a, b) #bilinmeyenleri bulmuş olur.
x

array([1.85714286, 2.71428571])