**NumPy: Numerical Python**
* Bilimsel hesaplamalar için kullanılır.
* Çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
* Temelleri 1995 yılında(martix-sig, Guido Van Rossum) atılmış, nihai olarak 2005(Travis Oliphant) yılında hayata geçmiştir.
* Listelere benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır.

### **Neden NumPy?**

In [3]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

In [4]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

**Daha fazla array olduğunda, matrislerin, vektörlerin çağrılması gerektiğinde ne yapmalıyız?**

In [16]:
import numpy as np

a = np.array([1, 2, 3, 4]) #numpy arrayi oluşturduk
b = np.array([2, 3, 4, 5])

a*b #az önceki işlemi, numpy sayesinde daha az çabayla yapabildik

array([ 2,  6, 12, 20])

**Not:** Veri saklama açısından numpy daha verimlidir. Normalde array içerisindeki elemanların her birisi için tip bilgisi tutulur, ama numpy array'inde sadece tek bir tip tutulur, bu da o array'in tipini ifade eder.

### **NumPy Array'i Oluşturma**

In [13]:
a = np.array([1, 2, 3, 4]) #numpy arrayi oluşturduk
type(a)

numpy.ndarray

In [10]:
np.array([3.14, 2, 3, 4]) #sabit tip baskısı olduğu için hepsini float tipe çevirir.

array([3.14, 2.  , 3.  , 4.  ])

In [12]:
np.array([3.14, 2, 3, 4], dtype = "int") #tüm elemanları int tipine cast eder.

array([3, 2, 3, 4])

In [15]:
np.zeros(10) #tamamı 0 olan, 10 elemanlı array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10, dtype = int) #tamamı 0 olan, tipi int olan, 10 elemanlı array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3, 5)) #elemanları 1 olan, 3 satır 5 sütunluk, 2 boyutlu array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones((3, 5), dtype = int) #elemanları 1 olan, tipi int olan, 3 satır 5 sütunluk, 2 boyutlu array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.full((3, 5), 3) #elemanların tamamı 3 olan, 3 satır 5 sütunluk, 2 boyutlu array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [25]:
np.arange(0, 31, 3) #0'dan 31'e kadar, 3'er artacak şekilde doğrusal bir array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [27]:
np.linspace(0, 1, 10) #0 ile 1 arasında 10 tane sayı oluşturur

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [30]:
np.random.normal(10, 4, (3, 4)) #ortalaması 10, standart sapması 4 olan, 3 satır 5 sütunluk 2 boyutlu array(matris)

array([[ 6.74203595,  7.97681827,  7.21503515, 13.36654037],
       [ 8.40492114,  4.67289842,  8.47882507,  5.29689739],
       [11.14023812,  8.83338883,  7.85075296, 10.64188391]])

In [33]:
np.random.randint(0, 10, (3, 3)) #0 ile 10 arasındaki sayılardan rastgele oluşan, 3*3 array

array([[4, 2, 2],
       [1, 3, 9],
       [7, 7, 1]])

### **NumPy Array Özellikleri**

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

**Tek Boyutlu Array**

In [39]:
a = np.random.randint(10, size=10)
a

array([2, 1, 0, 2, 0, 1, 7, 0, 5, 7])

In [41]:
a.ndim #tek boyutlu olduğu için çıktı 1 olur

1

In [43]:
a.shape #tek boyutlu olduğu için 1 boyut bilgisi verir ve bu boyutun da büyüklüğü 10'dur

(10,)

In [45]:
a.size #10 elemanlı

10

In [47]:
a.dtype

dtype('int32')

**İki Boyutlu Array**

In [49]:
b = np.random.randint(10, size = (3, 5))
b

array([[3, 9, 3, 4, 2],
       [2, 2, 7, 5, 8],
       [7, 1, 4, 8, 5]])

In [51]:
b.ndim #2 boyutlu olduğu için çıktı 2 olur

2

In [53]:
b.shape #3*5

(3, 5)

In [54]:
b.size

15

In [55]:
b.dtype

dtype('int32')

### **Reshaping**

Bazen fonksiyonlarda, döngülerde oluşan arrayleri, tek boyutta çoklu boyuta veya çoklu boyutta tek boyuta dönüştürme ihtiyacı olabiliyor. Bu gibi ihtiyaçlarda ***reshape*** fonksiyonundan yararlanılıyor.

In [58]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a.ndim

1

In [68]:
b = a.reshape((1, 9))
b #vektörün taşıdığı bilgiyi taşır, ama 1 satır 9 sütundan oluşur

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [67]:
b.ndim

2

 ### **Array Concatenation**

**Tek Boyutlu Array**

In [75]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [70]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [71]:
z = np.array([7, 8, 9])

In [74]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**İki Boyutlu Array**

In [77]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [79]:
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [80]:
np.concatenate([a, a], axis=0) #x axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [82]:
np.concatenate([a, a], axis=1) #y axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### **Array Splitting**

**Tek Boyutlu Array**

In [86]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1]) 

In [94]:
np.split(x, [3, 5]) #3'e kadarını, 5'e kadarını ve geri kalanı 3 parçaya ayırdı

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [90]:
a, b, c = np.split(x, [3, 5]) #oluşan 3 array'i a, b ve c değişkenlerine ata

In [91]:
a

array([1, 2, 3])

In [92]:
b

array([99, 99])

In [93]:
c

array([3, 2, 1])

**İki Boyutlu Array**

In [96]:
x = np.arange(16).reshape(4, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
np.vsplit(x, [2]) #2. indexe kadarını böler, vertical

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [101]:
ust, alt = np.vsplit(x, [2]) #ayrılan 2 array'i değişkenlerde tutabiliriz

In [102]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [103]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
np.hsplit(x, [2]) #horizontal

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [107]:
sag, sol = np.hsplit(x, [2])

In [108]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [109]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### **Array Sorting**

**Tek Boyutlu Array**

In [117]:
v = np.array([3, 6, 4, 1, 5])
v

array([3, 6, 4, 1, 5])

In [111]:
np.sort(v)

array([1, 3, 4, 5, 6])

In [112]:
v

array([3, 6, 4, 1, 5])

In [115]:
v.sort() #dangerous
v

array([1, 3, 4, 5, 6])

**İki Boyutlu Array**

In [118]:
m = np.random.normal(20, 5, (3, 3))
m

array([[18.40684107, 14.41484485, 11.67020106],
       [30.58253178, 26.15346502, 13.32160469],
       [32.3014845 , 14.67564073, 16.14407849]])

In [119]:
np.sort(m, axis = 1) #her satırı kendi içinde sıralar

array([[11.67020106, 14.41484485, 18.40684107],
       [13.32160469, 26.15346502, 30.58253178],
       [14.67564073, 16.14407849, 32.3014845 ]])

In [120]:
np.sort(m, axis = 0) #her sütunu kendi içinde sıralar

array([[18.40684107, 14.41484485, 11.67020106],
       [30.58253178, 14.67564073, 13.32160469],
       [32.3014845 , 26.15346502, 16.14407849]])